### PR TITLE
refactor: updated API authentication information.

### LINKED ISSUE #116: Investigate new JLR API restrictions
JLR have seemingly blocked third party access to it's APIs. Need to investigate exactly what they have done.

### PR DESCRIPTION
**Pull request by ardevd**
added new required headers for InControl API access.

Fixes #116

### CODE REVIEW

**Review by ardevd — COMMENTED** [review]
LGTM!

**Comment by z7x** [comment]
Beautiful, my "Siri, start my Jaaaag" shortcut is back up and running again 💪🏼

**Comment by christof-sohn** [comment]
Thank you very much, do you have any idea what this change is all about? Why is JLR doing this?

**Comment by ardevd** [comment]
> Beautiful, my "Siri, start my Jaaaag" shortcut is back up and running again 💪🏼
> 
> 
> 
> PS. is the "app-secret" always the same?

Yep, though there is a separate one for the Land Rover equivalent vehicles but they both work interchangeably.

**Comment by ardevd** [comment]
> Thank you very much, do you have any idea what this change is all about? Why is JLR doing this?

I have no official word. I could presume JLR wants to clamp down on third party apps in the name of control and security, but it's such a lazy effort that it's almost hard to believe.

**Comment by z7x** [comment]
It looks like something changed again yesterday between 11 and 11:30 am. The "loginuser" requests worked in the morning and now I get the same error "ProxyAuthorizationRequired" Code 407 as before. So I wonder if JLR will change the "app secret" every two weeks or what 🤬

**Comment by ardevd** [comment]
Yeah I'm looking at it. A bit more complicated this time due to all the measures put in place in the app to prevent snooping.

**Pull request merged**
