### PR TITLE
Modern code standards and new functions

### PR DESCRIPTION
**Pull request by msp1974**
@ardevd hope you are well.  I am back deveoping and supporting the JLR integration for Home Assistant, utilising your great api here.  As I have been working through updating it to better function with current HA, I have done a little rework on the code to update it to modern python standards and added some new functions.  Hope this is ok and you can merge.  Let me know if any issues.  Changes as below.  

1. Move to requests library
2. Used enum classes for server endpoints instead of global variables
3. Refactored strings to use f-string
4. Added waua status
5. Added disable guardian mode
6. Added disable service mode
7. Added disable transport mode

Appreciate a number of changes but if you could look at this for me as I want to issue a new HA integration version out to the user community and need to the new disable functions as part of that.

Thanks & kind regards,
Mark

### CODE REVIEW

**Comment by ardevd** [comment]
Really appreciate the contribution. I'll review it asap.

**Comment by ardevd** [comment]
@msp1974 a few notes:

- The `requests` package is now required. Hence, a requirements.txt file should be included with the necessary dependency.
- Has the usage changed? Your enums doesnt seem to work properly.  `f"{self.base.IFAS}/tokens"` returns `BaseURLs.IFAS/tokens` and hence the requests fail with the following error:

`requests.exceptions.MissingSchema: Invalid URL 'BaseURLs.IFAS/tokens': No scheme supplied. Perhaps you meant https://BaseURLs.IFAS/tokens?`

**Comment by msp1974** [comment]
Let me look at that as was working fine when tested.

**Comment by msp1974** [comment]
I have no clue what I did there....must stop drinking!!

Have made just an object class instead of enum and all tested as expected.
Also added requirements.txt and install_requires in setup.py.

**Review by ardevd — APPROVED** [review]
LGTM

**Comment by ardevd** [comment]
Thank you again very much for your contribution.

**Pull request merged**
